### ISSUE TITLE
Consider changing the trial method from 30 days limitation to 2 hours per day limitation

### ISSUE THREAD

**Issue by rp1231** [WindowTop/WindowTop-App#244]
Got trial expired on first run from windows store.
Installed the exe afterwards and got the same message.
Would that be because I installed the windows store version first and it declared my pc as trial expired?

**Comment by gileli121** [comment]
Hi
The check is per unique hardware UDID that generated for each computer.
The unique udid doesn't contain any private information

It is the same check in the store version and the regular version.

It verify if you can start the trial using backend server and the unique computer hardware UDID

If you really want to bypass it instead of support the hard work of it, you can block the internet connection to the app via firewall but you will have to remove app settings each 30 days because it count it locally

But if you really want the full functionality, the best option is to purchase it. Windows itself cost a lot more so the small price here is very small addition :)

**Comment by gileli121** [comment]
@rp1231 
Did you started the app more than 30 days ago?
If yes then it is the expected behaviour.

If no then it is a bug

**Comment by rp1231** [comment]
@gileli121 no this was on first run.
This was the first time I installed it.

**Comment by gileli121** [comment]
@rp1231 
Please try to install this older version
https://github.com/BiGilSoft/WindowTop/releases/tag/v5.13.1

Let me know if you still get the same issue

**Comment by rp1231** [comment]
This is the screenshot of the license page.
![WindowTop_yeakjKCfsf](https://user-images.githubusercontent.com/47380919/178434260-8364f59c-313e-4f50-8c66-a901b9c33798.png)
Is it supposed to have an activate trial button somewhere?

**Comment by gileli121** [comment]
@rp1231 
Long time ago there was such button to start trial but it removed and instead it just automatically start the trial without asking.

About the issue, I will return back to you later today to analyze the issue better.

Sorry about the issue

**Comment by rp1231** [comment]
Hi, I have uploaded the files.

[WindowTop.zip](https://github.com/BiGilSoft/WindowTop/files/9095392/WindowTop.zip)

**Comment by gileli121** [comment]
@rp1231 
There is a record that you installed and started it at 2022-01-04T07:13:39Z
But I understand the issue here.. if someone installed it and run it only once, then maybe no need to count it if you did not use it.

I deleted the record.
Please delete the settings and start the app again.
You should get the 30 days back now.

Please try it during this time and let me know how it works, and any feedback is welcome.

**Comment by gileli121** [comment]
@rp1231 

I wonder if maybe there is a better idea on how to implement the trial mode.
Maybe I make the trial never expire if you count days but at the same time, make it expire each day after 3 hours of using the advanced features.

This way no need to store all of this data in the backend, and users even get more time to try the app and think if they want to purchase, and while I still limit them to give them a reason to support the project and pay.

Maybe this is much better

**Comment by rp1231** [comment]
I keep trying out a lot of such apps,
So maybe I must have installed it before....
But I usually remember the apps I try out.....
I dunno.....

**Comment by gileli121** [comment]
So maybe the computer UDID is not unique after all.
This is the only way to reproduce this issue.

Anyway, if I will switch the way of counting 30 days (that is not necessary counts 30 days of **active** usage) to the way to limit usage to about 2 hours a day, it will fix such an issue and also solve cases like yours that it count days that you did not really try it during the days.

It will not even need a backend to make such a trial mode, no need to store unique UDIDs 
I think that I will give it a try. At worse, I will revert it.

The 2 hours limit will be for all the pro stuff.


You said that you don't have a problem with the 30 days limit idea. But you just had one and opened an issue exactly about it.
Do you have a problem with 2 hours limit per day? For me, it is easier to implement and I see here good advantages.
But I want to see your feedback

**Comment by rp1231** [comment]
What I meant was that I don't mind the 30 day trial idea if it works properly.
I don't know if I am the only one who encountered this problem or this has happened to others as well.

But I don't mind the idea with the timer you've suggested as well.
As long as the users get to test drive the
app. And two hours is a good amount of time to try out the features.

**Comment by rp1231** [comment]
I think maybe the microsoft store has a trial apps option as well.
So maybe you can use the microsoft store's trial mehtod instead of implementing your own?
I have seen the "Free trial" button below the apps in the microsoft store.
I've seen this button on windows 11 so I don't know if this button exists on the windows 10 app store.
But that wouldn't solve the trial problem for the standalone exe though.......

**Comment by gileli121** [comment]
@rp1231 
Some time ago I used the Microsoft store service also for the trial.

But I decided not to do it because to start MS Store trial, you need to log in/register to a Microsoft account and not everyone does it. I want to give people the option to start the trial with the minimum amount of effort.

I will test the new idea of the trial mode.
I think that I never saw any app that does such a trial method but I see a lot of benefits here.
I can market it as "*FREE" ( * For 2 hours per day for pro features). I can use the word "FREE" and at the same time, still make it a trial and give people a reason purchase it and support the project, and give them unlimited time to consider it (to not lose any chance that they will decide to purchase it)

**Comment by gileli121** [comment]
I updated the title

**Comment by rp1231** [comment]
Oh ok.
Makes sense.

**Comment by gileli121** [comment]
This task is scheduled to be developed by the end of the next weekend

**Comment by gileli121** [comment]
According to chat.openai.com (ChatGPT.. the AI that one day will replace us all), it is unlikely that the computer GUID will not be unique 
![image](https://user-images.githubusercontent.com/17680514/209433498-d3329498-3fe4-491d-be38-06c09312333d.png)

It may be possible issue for virtual machines

**Comment by gileli121** [comment]
Closed until I will reconsider again
