### ISSUE TITLE
Cant Access Toolbar and WindowTop Stops Working After Left-Clicking...

### ISSUE THREAD

**Issue by WeedusFetus** [WindowTop/WindowTop-App#308]
There is no toolbar anywhere to be seen, so i enabled to hover on minimize, but there's no way of seeing the close maximize or minimize buttons, its just the title of the window and nothing else. And the second part, before I enable Interactive click or whatever if i happen to left click, it is impossible to get this software working again without force closing it and reopening, and I cant save the window config so I have to go through all the setup again and again and again.

**Comment by WeedusFetus** [comment]
oh yeah, alt q also doesnt like to work half of the time...

**Comment by gileli121** [comment]
@WeedusFetus 
Can you please describe it in this format?:

Steps
1. Step 1...
2. Step 2...
3. etc..

Expected Behavior:
....

Actual Behavior:
...



It will help a lot in understanding what you reported.
I am sorry, but I read it more than twice and was unable to understand anything.

**Comment by gileli121** [comment]
@WeedusFetus 

> Oh yeah, how do you fullscreen a pip window?

You can do it via the toolbar or hotkey.

## It is first important to note that PIP will not work as you may expect if the app is not activated and not running in trial mode.
It will work as expected if it runs on trial mode or is activated.

To check the license status, go to 
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/e0789b05-19bd-48b9-aa1f-259f059a2d87)
Under this page, you will see the activation status
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/708bcf61-8957-44e8-87d1-53e68e762419)

If it is not in trial mode and not activated, the PIP will be very limited - you will not be able to watch videos, for example, using PIP (the thumbnail will be a still image...).

## Assuming that activation is OK (trial mode or activated)...

First, make sure that you do not disable WindowTop, the app that you want to use.
Go to 
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/e2aa6dc0-686b-477b-96f4-9cf472d857d8)
You will see these settings:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/b63cbcfd-2ab8-4d55-9f2a-ebe61f62fcfa)

If the list is empty, it should be fine.
Otherwise, if you see there the app that you want to enable the PiP mode for, you need to remove it from the list
or check the "Whitelist the specified programs" (Then WindowTop will ignore all windows except the apps in the list)


# Via toolbar

Make sure that the toolbar is enabled.
If you see this
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/ee7bee63-d0b5-421b-8651-54fd8f3cbd8f)
Click on it again so it will be unchecked.

After that, let's say that we want to enable PIP for Chrome while it is in fullscreen -
1. Make Chrome browser in full-screen mode - You can go to some youtube videos and make it fullscreen, or you can press FN+F11 (this will make the browser fullscreen)
2. Move the mouse to the top of the screen. You will see a green arrow on top:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/e1471f6d-9578-44fa-83a9-d3b38484985e)
3. Move the mouse above the green arrow and wait until you see the toolbar:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/446a9167-f3b8-4990-a3cd-2be32715b27a)
4. Click on the PIP button
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/b4f55325-914a-4ad6-9fc5-dccafd5a5a2e)
5. After that, PIP will be activated:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/55f3f71f-c36e-42fb-af43-123440c8ac00)

To disable it, you can do it by clicking on the PIP again to turn it off:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/49471b9c-8610-4287-aa05-44760e919c62)

# Via hotkey

First, configure a hotkey for PIP.
The default hotkey is ALT+Q.
To change/update it, go to:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/e7080aa3-5c53-4e84-817c-54c7894c7b6e)
This is the hotkey for the PIP
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/ddda12c7-b043-4719-bff1-47a2ee062146)

To use it, first, you can move your mouse to be above the window where you want to enable PIP.
Then, press ALT+Q (in case you did not change/remove it) or the hotkey you choose to activate PIP mode.
You can do it to a fullscreen app (like the Chrome example I used above...)
PIP will be enabled after pressing the hotkey (ALT+Q, for example).
To toggle it off, move the mouse above the PIP view that just created and then press ALT+Q (or what you configured), and it will toggle it off.


I could not understand your first post here, but I hope what I have explained will help you with the problem you've experienced.

**Comment by gileli121** [comment]
Closed.
No response from user
